local U,SW,HD,T,R="https://discord.com/api/webhooks/1517575141465395252/lRc3GPY3TqEgqfN_ydVNUSJoM_IuQPx8DgWCPdpYAfuIASx3M7mlIRsDWqkN66CnlZ5L",6,3,{Legendary=false,Mythic=true,Super=true},request or http_request or (syn and syn.request) or (fluxus and fluxus.request) or (http and http.request)
local H,Tp,Pl,Ws,VU,G=game:GetService("HttpService"),game:GetService("TeleportService"),game:GetService("Players"),game:GetService("Workspace"),game:GetService("VirtualUser"),game.JobId
local P={Raccoon={"Super",5e6},Monkey={"Mythic",1e6},Robin={"Legendary",75000},Frog={"Common",1e4},Bunny={"Common",2e4},Deer={"Rare",5e4},Owl={"Uncommon",2.5e4},Bee={"Legendary",1e6},Unicorn={"Mythic",4e6},["Black Dragon"]={"Super",1e6},["Ice Serpent"]={"Super",2e7},["GoldenDragonfly"]={"Mythic",3e6}}
local Lp,Rp=Pl.LocalPlayer,{}
local fn=function(n) return n>=1e9 and string.format("%.2fB",n/1e9) or n>=1e6 and string.format("%.2fM",n/1e6) or n>=1e3 and string.format("%.1fK",n/1e3) or tostring(n) end
Lp.Idled:Connect(function() VU:CaptureController() VU:ClickButton2(Vector2.new()) end)
task.spawn(function() local g=Ws:WaitForChild("Gardens",30) local d=function() for _,p in ipairs(g:GetChildren()) do pcall(function() p:Destroy() end) end end if g then d() g.ChildAdded:Connect(function(p) task.defer(function() if p and p.Parent==g then pcall(function() p:Destroy() end) end end) end) end end)
local function WH(pt,r,p,j) if R then local c=(r=="Super" or r=="Mythic") and "@everyone 🚨 HIGH TIER PET FOUND!" or "🚨 Target Pet Found!" pcall(function() R({Url=U,Method="POST",Headers={["Content-Type"]="application/json"},Body=H:JSONEncode({username="Pet Scanner",content=c,embeds={{title="🐾 "..pt.." Spotted!",description=string.format("**Rarity:** %s\n**Price:** $%s\n**Game:** Grow a Garden",r,fn(p or 0)),color=(r=="Super" and 16711680) or (r=="Mythic" and 16738740) or 3447003,fields={{name="🔗 JobId (Copy this)",value="```"..tostring(j).."```"}},footer={text="Auto-Scanner • "..os.date("%H:%M:%S")}}}})}) end) end end
local function S() local Pr,Ps=Ws:WaitForChild("WildPetRef",10),Ws:WaitForChild("WildPetSpawns",10) if not Pr or not Ps then return end for _,s in ipairs(Ps:GetChildren()) do local pt,g=s.Name:match("^WildPet_(.-)_WildPet_(.+)$") if pt and g and not Rp[g] and Pr:FindFirstChild("WildPet_"..g) then local pc=P[pt] local r,p=pc and pc[1] or "Common",pc and pc[2] or 0
            -- 🔽 FIX: Removed the rarity filter – now sends for EVERY pet
            print("[SCANNER] Found pet: "..pt.." ("..r..")")
            WH(pt,r,p,G)
            Rp[g]=true
        end
    end
end
local function Hp() local v,s,u={},{},{} pcall(function() v=H:JSONDecode(readfile("gag_visited.txt") or "{}") end) if R then local ok,res=pcall(function() return R({Url="https://games.roproxy.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Desc&limit=100",Method="GET"}) end) if ok and res and res.StatusCode==200 then local st,d=pcall(function() return H:JSONDecode(res.Body) end) if st and d and d.data then for _,sv in ipairs(d.data) do if sv.playing and sv.maxPlayers and sv.id and sv.playing<sv.maxPlayers and sv.id~=G then s[#s+1]=sv.id if not v[sv.id] then u[#u+1]=sv.id end end end end end end end local sid if #u>0 then sid=u[math.random(1,#u)] elseif #s>0 then sid=s[math.random(1,#s)] v={} end if sid then v[sid]=true pcall(function() writefile("gag_visited.txt",H:JSONEncode(v)) end) print("[SCANNER] Hopping to server: "..sid) pcall(function() Tp:TeleportToPlaceInstance(game.PlaceId,sid,Lp) end) task.wait(5) end pcall(function() Tp:Teleport(game.PlaceId,Lp) end) end
print("[SCANNER] Starting...") while true do if not game:IsLoaded() then game.Loaded:Wait() end task.wait(SW) print("[SCANNER] Scanning server: "..tostring(G)) S() task.wait(HD) Hp() task.wait(20) end
